import { TComponents } from '@sandbox/ui'

export const components: TComponents = {
  AtomBackground: () => import('@apparatus/blocks-atoms-background/meta' /* webpackChunkName: "AtomBackground" */),
  AtomBorder: () => import('@apparatus/blocks-atoms-border/meta' /* webpackChunkName: "AtomBorder" */),
  AtomFootprint: () => import('@apparatus/blocks-atoms-footprint/meta' /* webpackChunkName: "AtomFootprint" */),
  AtomIcon: () => import('@apparatus/blocks-atoms-icon/meta' /* webpackChunkName: "AtomIcon" */),
  AtomInput: () => import('@apparatus/blocks-atoms-input/meta' /* webpackChunkName: "AtomInput" */),
  AtomSpacer: () => import('@apparatus/blocks-atoms-spacer/meta' /* webpackChunkName: "AtomSpacer" */),
  AtomText: () => import('@apparatus/blocks-atoms-text/meta' /* webpackChunkName: "AtomText" */),
  ContextInterface: () => import('@apparatus/blocks-contexts-interface/meta' /* webpackChunkName: "ContextInterface" */),
  ActionSheet: () => import('@apparatus/blocks-molecules-action-sheet/meta' /* webpackChunkName: "ActionSheet" */),
  Bottom: () => import('@apparatus/blocks-molecules-bottom/meta' /* webpackChunkName: "Bottom" */),
  Button: () => import('@apparatus/blocks-molecules-button/meta' /* webpackChunkName: "Button" */),
  ButtonIcon: () => import('@apparatus/blocks-molecules-button-icon/meta' /* webpackChunkName: "ButtonIcon" */),
  Card: () => import('@apparatus/blocks-molecules-card/meta' /* webpackChunkName: "Card" */),
  ChatBubble: () => import('@apparatus/blocks-molecules-chat-bubble/meta' /* webpackChunkName: "ChatBubble" */),
  ContextHeader: () => import('@apparatus/blocks-molecules-context-header/meta' /* webpackChunkName: "ContextHeader" */),
  DateInput: () => import('@apparatus/blocks-molecules-date-input/meta' /* webpackChunkName: "DateInput" */),
  FullCover: () => import('@apparatus/blocks-molecules-full-cover/meta' /* webpackChunkName: "FullCover" */),
  Input: () => import('@apparatus/blocks-molecules-input/meta' /* webpackChunkName: "Input" */),
  ListOption: () => import('@apparatus/blocks-molecules-list-option/meta' /* webpackChunkName: "ListOption" */),
  MainScrollable: () => import('@apparatus/blocks-molecules-main-scrollable/meta' /* webpackChunkName: "MainScrollable" */),
  SideNavigation: () => import('@apparatus/blocks-molecules-side-navigation/meta' /* webpackChunkName: "SideNavigation" */),
  StickyButton: () => import('@apparatus/blocks-molecules-sticky-button/meta' /* webpackChunkName: "StickyButton" */),
  TabSelector: () => import('@apparatus/blocks-molecules-tab-selector/meta' /* webpackChunkName: "TabSelector" */),
  Text: () => import('@apparatus/blocks-molecules-text/meta' /* webpackChunkName: "Text" */),
  TimeInput: () => import('@apparatus/blocks-molecules-time-input/meta' /* webpackChunkName: "TimeInput" */),
  Toast: () => import('@apparatus/blocks-molecules-toast/meta' /* webpackChunkName: "Toast" */),
  Toggle: () => import('@apparatus/blocks-molecules-toggle/meta' /* webpackChunkName: "Toggle" */),
}

